name: "Release per-commit snapshots"
on: push

jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish snapshot
      run: ./gradlew publish
      env:
        USERNAME: msfjarvis
        PASSWORD: ${{ secrets.PACKAGES_TOKEN }}
